# Generated by Django 5.1.3 on 2024-11-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_cat_remove_eeci_cat_id_eeci_cat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eeci',
            new_name='panel',
        ),
    ]
