# Generated by Django 5.1.3 on 2024-11-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_rename_eeci_panel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='cat',
            field=models.CharField(choices=[('1', 'Менеджер'), ('2', 'Тренер'), ('3', 'Клиент')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
